packages <- c("tidyverse", "httr","jsonlite", "rvest", "stringr", "data.table")

install.packages("tidyverse")
install.packages("httr")
install.packeges("rvest")
install.packages("jsonlite")
install.packages("stringr")
install.packages("data.table")
install.packages("esquisse")
install.packages("fable")
install.packages("Hmisc")


length(installed.packages())
library('tidyverse')
library('httr')
library("jsonlite")
library("rvest")
library("stringr")
library("data.table")
library("fable")
library("tsibble")
library("esquisse")
library("Hmisc")
